---
driver:
  name: terraform
  variables:
    aws_ssh_key_name: "<%= ENV['AWS_SSH_KEY_ID'] %>"
    aws_access_key: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
    aws_secret_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
    aws_instance_type: "<%= ENV['AWS_DEFAULT_INSTANCE_TYPE'] %>"
    aws_subnet_id: "<%= ENV['AWS_SUBNET_ID'] %>"
    aws_bucket_prefix: "<%= ENV['AWS_KEY_NAME'] %>"
    aws_region: "<%= ENV['AWS_REGION'] %>"
    aws_ami_id: "<%= ENV['AWS_AMI_ID'] %>"
    aws_security_group: "<%= ENV['AWS_SG_ID'] %>"

provisioner:
  name: terraform

platforms:
  - name: ubuntu

transport:
  name: ssh
  # ssh_key: "<%= ENV['AWS_SSH_KEY_ID'] %>"

verifier:
  name: terraform
  #format: json
  #output: "%{platform}_%{suite}-<%= Time.now.iso8601 %>.json"
  groups:
    - name: aws-demo-baseline

suites:
  - name: aws-demo-baseline



